import Mongoose from 'mongoose';

export const userProjection = {
  _id: 1,
  uid: 1,
  name: 1,
  username: 1,
  referral_code: 1,
  updatedAt: 1,
  createdAt: 1,
  beta_code: 1,
  bio: 1,
  birthday: 1,
  cover_pic: 1,
  cryptocurrencies: 1,
  default_tag: 1,
  followers_count: 1,
  following_count: 1,
  geoip: 1,
  location: 1,
  meta: 1,
  profile_pic: 1,
  settings: 1,
  shards: 1,
  tagline: 1,
  type: 1,
  userCareerList: 1,
  userEducationList: 1,
  xchange: 1,
  message_count: 1,
  notification_count: 1,
  is_mission_unlock: 1,
  user_achievement: 1,
  current_shards: 1,
  current_dust: 1,
  dust: 1,
  platform_username: 1,
  watchList: 1,
  badge: 1,
  is_following: 1,
  team: 1,
  avatarImage: 1,
  email: 1,
  country_code: 1,
  phone: 1,
  isNewRelease: 1,
  additional_details: 1,
  isMFAEnabled: 1,
  founded: 1,
  headquarters: 1,
  industry: 1,
  website: 1,
  description: 1,
  nft: 1,
  socialmediaLinks: 1,
  cryptocurrency: 1,
  mission_points: 1,
  isNewAnnouncement: 1,
  roles: 1,
  isCurator: 1,
};

export const convertToMongoID = (id) => Mongoose.Types.ObjectId(id);
